# Generated by Django 3.1.4 on 2020-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='keywordstr',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
