# Generated by Django 3.1.4 on 2020-12-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_paper_keywordstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='paper_num',
        ),
    ]
