# Generated by Django 3.1.4 on 2020-12-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201216_1959'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['pid'], name='pid'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['title'], name='title'),
        ),
    ]
