# Generated by Django 3.1.4 on 2020-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_venue_paper_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authornamestr',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
