# Generated by Django 3.0.3 on 2020-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20201217_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='n_citation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='paper_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='display_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='venue',
            name='normalized_name',
            field=models.CharField(max_length=500),
        ),
    ]
