# Generated by Django 3.1.4 on 2020-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_paper_authornamestr'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authorofpaper',
            index=models.Index(fields=['paper_id'], name='paper_id'),
        ),
    ]
