# Generated by Django 3.0.3 on 2020-12-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20201219_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='paper_num',
        ),
    ]
