# Generated by Django 3.1.4 on 2020-12-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20201220_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
