# Generated by Django 3.0.3 on 2020-12-22 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_venue_paper_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Author'),
            preserve_default=False,
        ),
    ]
