# Generated by Django 3.1.4 on 2020-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_paper_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
