# Generated by Django 3.1.4 on 2020-12-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_author_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['field'], name='field'),
        ),
    ]
