# Generated by Django 3.1.4 on 2020-12-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20201222_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='field',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
