# Generated by Django 3.1.4 on 2020-12-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20201222_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
