# Generated by Django 3.1.4 on 2020-12-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20201222_1101'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['h_index'], name='h_index'),
        ),
    ]
